language: node_js
node_js:
  - 10

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # BUILD API FEED IMAGE
  - docker build -t udagram-api-feed ./udagram-api-feed/
  - docker tag udagram-api-feed kelue/udagram-api-feed:v2
  # BUILD FRONTEND IMAGE
  - docker build -t udagram-frontend ./udagram-frontend/
  - docker tag udagram-frontend kelue/udagram-frontend:v2
  # BUILD REVERSE PROXY IMAGE
  - docker build -t reverseproxy ./udagram-reverseproxy/
  - docker tag reverseproxy kelue/reverseproxy:v2
  # BUILD USER API IMAGE
  - docker build -t udagram-api-user ./udagram-api-user/
  - docker tag udagram-api-user kelue/udagram-api-user:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # PPPPPPPPPPUSH ALL IMAGES TO DOCKER
  - docker push kelue/udagram-api-feed:v2
  - docker push kelue/udagram-api-user:v2
  - docker push kelue/udagram-frontend:v2
  - docker push kelue/reverseproxy:v2