language: node_js
node_js:
  - 10

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed/
  - docker tag udagram-api-feed kelue/udagram-api-feed:latest
  - docker build -t udagram-frontend ./udagram-frontend/
  - docker tag udagram-frontend kelue/udagram-frontend:latest
  - docker build -t reverseproxy ./reverseproxy/
  - docker tag reverseproxy kelue/reverseproxy:latest
  - docker build -t udagram-api-user ./udagram-api-user/
  - docker tag udagram-api-user kelue/udagram-api-user:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kelue/udagram-api-feed:latest
  - docker push kelue/udagram-api-user:latest
  - docker push kelue/udagram-frontend:latest
  - docker push kelue/reverseproxy:latest