apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: kelue/reverseproxy:v2
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    run: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
  selector:
    run: reverseproxy
  type: LoadBalancer